// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppApp: typeof import('./../src/components/AppApp/AppApp.vue')['default']
    Button: typeof import('./../src/components/Button/Button.vue')['default']
    ModelPreview: typeof import('./common/ModelPreview.vue')['default']
  }
}

export { }
